name: Testing, create changelog and release
on:
  push:
    tags:
      - "v*"
jobs:
  test:
    uses: ./.github/workflows/tests.yml
  build-and-release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: "go.mod"
          token: ${{ github.token }}
          cache-dependency-path: "go.sum"
      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: /tmp/CHANGELOG.md
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          args: release --clean --release-notes /tmp/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
